- name: Installing supporting packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - cri-tools
      - kubernetes-cni
      - socat
      - ebtables
- name: Remove swapfile from /etc/fstab
  mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
  with_items:
      - swap
      - none