- name: Assigning multiple IPs to the worker NICs  
  shell: |
   for i in {1..10}; do az network nic ip-config create --name ipconfig-$i --nic-name worker-0-nic -g kubernetes \
   --private-ip-address 10.240.20.$i ;done
   for i in {1..10}; do az network nic ip-config create --name ipconfig-$i --nic-name worker-1-nic -g kubernetes \
   --private-ip-address 10.240.21.$i ;done
   for i in {1..10}; do az network nic ip-config create --name ipconfig-$i --nic-name worker-2-nic -g kubernetes \
   --private-ip-address 10.240.22.$i ;done