- name: Restart kubelet
  service:
        name: kubelet
        daemon_reload: yes
        state: restarted

- name: Adding handler to kubelet
  handlers:
  - name: docker status
    service: name=docker state=started 