- hosts: controlvms[0]
  become: yes
  gather_facts: false
  tasks:
    - name: Creating kubeadm.out file
      command: touch /home/kuberoot/kubeadm.output
    - name: Copy file to remote machine
      copy:
        src: /home/kuberoot/azure_lb_pip
        dest: /home/kuberoot/azure_lb_pip
        mode: 0644
    - name: Get the LB PIP
      include_vars:
        file: /home/kuberoot/azure_lb_pip
        name: contents
      register: contents
    - debug: msg= {{ ansible_facts }}
    - name: Running kubeadm init
      command: kubeadm init --control-plane-endpoint {{ contents }}:6443 --upload-certs --pod-network-cidr 10.200.0.0/16 > /home/kuberoot/kubeadm.output
    - name: Setup kubeconfig for kuberoot user
      command: "{{ item }}"
      with_items:
      - mkdir -p /home/kuberoot/.kube
      - cp -i /etc/kubernetes/admin.conf /home/kuberoot/.kube/config
      - chown kuberoot:kuberoot /home/kuberoot/.kube/config
    - name: Install calico pod network
      become: false
      command: kubectl create -f https://docs.projectcalico.org/v3.4/getting-started/kubernetes/installation/hosted/calico.yaml
