- hosts: controlvms[0]
  become: yes
  gather_facts: false
  tasks:
    - name: Creating kubeadm.out file
      command: touch /home/kuberoot/kubeadm.output
    - name: Initialize the Kubernetes cluster using kubeadm
      vars:
        contents: "{{ lookup('file', '/home/kuberoot/azure_lb_pip') }}"
    - debug: msg= {{ contents }}
    - name: Running kubeadm init
      command: kubeadm init --control-plane-endpoint {{ contents }}:6443 --upload-certs --pod-network-cidr 10.200.0.0/16 > /home/kuberoot/kubeadm.output
    - name: Setup kubeconfig for kuberoot user
      become_user: kuberoot
      file:
        path: /home/kuberoot/.kube
        state: directory
        mode: 0755
    - name: Copy admin.conf file to kuberoot directory
      copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/kubernetes/.kube/config
      owner: kuberoot
      group: kuberoot
    - name: Install calico pod network
      become: false
      command: kubectl create -f https://docs.projectcalico.org/v3.4/getting-started/kubernetes/installation/hosted/calico.yaml
