---
- hosts: controlvms[0]
  become: true
  tasks:
  - name: Update all packages to the latest version
    apt:
      upgrade: dist
  - name: Rebooting the node
    reboot:
      reboot_timeout: 5
  - name: Installing supporting packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present

  - name: Install docker and its dependecies
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    notify:
      - docker status

  - name: Add kuberoot user to docker group
    user:
      name: kuberoot
      group: docker

  - name: Remove swapfile from /etc/fstab
    mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
    with_items:
      - swap
      - none
  #- name: Disable swap
  #  command: swapoff -a
  #  when: ansible_swaptotal_mb > 0

  - name: Add an apt signing key for Kubernetes
    apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

  - name: Adding apt repository for Kubernetes
    apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list
  - name: Install Kubernetes binaries
    apt: 
        name: "{{ packages }}"
        state: present
        update_cache: yes
    vars:
        packages:
          - kubelet 
          - kubeadm 
          - kubectl

  #- name: Configure node ip
  #  lineinfile:
  #      path: /etc/default/kubelet
  #      line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}

  - name: Restart kubelet
    service:
        name: kubelet
        daemon_reload: yes
        state: restarted

  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --control-plane-endpoint 104.214.72.36:6443 --upload-certs --pod-network-cidr 10.200.0.0/16

  - name: Setup kubeconfig for kuberoot user
    file:
      path: /home/kuberoot/.kube
      state: directory
      mode: '0755'
  - name: Copy admin.conf file to kuberoot directory  
    copy:
     src: /etc/kubernetes/admin.conf
     dest: /home/kubernetes/.kube/config
     owner: kuberoot
     group: kuberoot
  - name: Install calico pod network
    become: false
    command: kubectl create -f https://docs.projectcalico.org/v3.4/getting-started/kubernetes/installation/hosted/calico.yaml

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to local file
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
  
  handlers:
    - name: docker status
      service: name=docker state=started