- hosts: controlvms[0]
  become: yes
  gather_facts: false
  tasks:
    - name: Get cluster join commands for worker and control nodes
      shell: |
        #cat /home/kuberoot/kubeadm.out|grep -A 3 'kubeadm join' > kubeadm.temp
        #sed -i '/^$/d' kubeadm.temp
        head -n 3 kubeadm.out > controlvms
        tail -n 2 kubeadm.out > workervms
    - name: Get the command for control plane
      tasks:
        command: cat /home/kuberoot/controlvms 
        register: controlvms
        local_action: copy content="{{ controlvms.stdout_lines[0] }}" dest="./controlvms"
    - debug: var=controlvms
    - name: Get the command for data plane
      tasks:
        command: cat /home/kuberoot/workervms 
        register: workervms
        local_action: copy content="{{ workervms.stdout_lines[0] }}" dest="./workervms"
    - debug: msg="{{ workervms.stdout }}"
      


- hosts: datavms
  become: yes
  tasks:
    - name: Joining worker VMs
      copy: src=workervms dest=/tmp/workervms.sh mode=0777
      command: sh /tmp/workervms.sh
      
- hosts: controlvms[1]
  become: yes
  tasks:
    - name: Joining to control plane
      copy: src=controlvms dest=/tmp/controlvms.sh mode=0777
      command: sh /tmp/controlvms.sh
- hosts: controlvms[2]
  become: yes
  tasks:
    - name: Joining to control plane
      copy: src=controlvms dest=/tmp/controlvms.sh mode=0777
      command: sh /tmp/controlvms.sh
      